#!/bin/bash

if [ ! -d wolfssl ]; then
  echo "info: cloning wolfssl"
  git clone https://github.com/philljj/wolfssl.git || exit 1
  #git co fedora_crypto_policy || exit 1
fi

cd wolfssl || exit 1

if [ ! -f configure ]; then
  ./autogen.sh || exit 1
fi

if [ $# -eq 1 ]; then
  echo "info: full rebuild"
  if [ -f configure ]; then
    rm configure
    autoreconf
  fi
fi

#./configure \
#  --with-sys-crypto-policy \
#  --enable-sslv3 \
#  --enable-oldtls \
#  --enable-tlsv10 \
#  --enable-debug \
#  --enable-opensslextra \

./configure \
  --enable-sslv3 \
  --enable-oldtls \
  --enable-tlsv10 \
  --enable-distro \
  --with-sys-crypto-policy \
  --enable-debug \
  || exit 1
make || exit 1
#sudo make install
