#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

cert1024="certs/rsa/1024/cert_1024.pem"
key1024="certs/rsa/1024/keypair_1024.pem"

pcy_legacy="crypto-policies/legacy/wolfssl.txt"
pcy_default="crypto-policies/default/wolfssl.txt"
pcy_future="crypto-policies/future/wolfssl.txt"

err_and_die() {
  echo -e "error: $1: ${RED}fail${NC}"
  exit 1
}

echo ""
echo "info: 1024 legacy"
./test/test_policy -c $cert1024 -k $key1024 -p $pcy_legacy -v || err_and_die "1024 legacy"

echo ""
echo "info: 1024 default"
./test/test_policy -c $cert1024 -k $key1024 -p $pcy_default  -v && err_and_die "1024 default"

echo ""
echo "info: 1024 future"
./test/test_policy -c $cert1024 -k $key1024 -p $pcy_future  -v && err_and_die "1024 future"


echo ""
echo -e "info: ${GREEN}pass${NC}"
