#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

err_and_die() {
  echo -e "error: $1: ${RED}fail${NC}"
  exit 1
}

cd wolfssl || exit 1

echo "tests to cover:"
./tests/unit.test --list | grep -i crypto_policy
echo ""

for test_no in `./tests/unit.test --list | grep -i crypto_policy | awk -F ':' '{print $1}'`; do

  if [ -z $test_no ]; then
    err_and_die "test_wolfSSL_crypto_policy not found"
  fi

  ./tests/unit.test -$test_no > /dev/null 2>&1 || err_and_die "unit.test -$test_no failed"
  echo "./tests/unit.test -$test_no: good"
done

echo ""
echo -e "info: ${GREEN}pass${NC}"
